version: '3'

services:
  postgres_db:
    build: ./db
    image: nbekenov/postgres-db
    environment:
      POSTGRES_DB: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.pg
  
  pg_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_db 
    env_file:
      - .env.pg_admin
    ports:
      - 80:80

volumes:
  database-data:
    external: false